### ISSUE TITLE
fix swatch grid

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/alala-carte#1]
1. white print swatch too zoomed in
2. last swatch drops down 
   <img width="364" alt="screen shot 2016-04-18 at 1 31 40 am" src="https://cloud.githubusercontent.com/assets/3649059/14594522/67b4d4cc-0505-11e6-9c29-e6ff8a0108b6.png">
3. heading should expand with swatches
   <img width="636" alt="screen shot 2016-04-18 at 4 40 32 am" src="https://cloud.githubusercontent.com/assets/3649059/14598450/408e4430-0520-11e6-91f4-21edfb620eb0.png">

**Comment by EmilioTelevision** [comment]
fixed
![image](https://cloud.githubusercontent.com/assets/3394886/14618564/364511d2-0581-11e6-8339-85a881a0548c.png)

**Comment by GVFTW** [comment]
not sure if im caching or what but im not getting images and last item is still dropping a bit on the swatch grid. i emptied cache and it still showed up like this

<img width="1258" alt="screen shot 2016-04-18 at 4 35 28 pm" src="https://cloud.githubusercontent.com/assets/3649059/14619080/b2cdff00-0583-11e6-8ff8-5277519e575f.png">

**Comment by GVFTW** [comment]
would also like to have swatch options 40px x 40px on desktop, and 50 x 50 on desktop like i left it off last night

**Comment by EmilioTelevision** [comment]
added

**Comment by EmilioTelevision** [comment]
fixed

**Comment by cascadiaderek** [comment]
Closing this ticket...
